export const countries = [
  { label: "Afghanistan", iso: "af" },
  { label: "Albania", iso: "al" },
  { label: "Algeria", iso: "dz" },
  { label: "Andorra", iso: "ad" },
  { label: "Angola", iso: "ao" },
  { label: "Anguilla", iso: "ai" },
  {
    label: "Antigua and Barbuda",
    iso: "ag",
  },
  { label: "Argentina", iso: "ar" },
  { label: "Armenia", iso: "am" },
  { label: "Aruba", iso: "aw" },
  { label: "Australia", iso: "au" },
  { label: "Austria", iso: "at" },
  { label: "Azerbaijan", iso: "az" },
  { label: "Bahamas", iso: "bs" },
  { label: "Bahrain", iso: "bh" },
  { label: "Bangladesh", iso: "bd" },
  { label: "Barbados", iso: "bb" },
  { label: "Belarus", iso: "by" },
  { label: "Belgium", iso: "be" },
  { label: "Belize", iso: "bz" },
  { label: "Benin", iso: "bj" },
  { label: "Bermuda", iso: "bm" },
  { label: "Bhutan", iso: "bt" },
  { label: "Bolivia", iso: "bo" },
  {
    label: "Bosnia and Herzegovina",
    iso: "ba",
  },
  { label: "Botswana", iso: "bw" },
  { label: "Brazil", iso: "br" },
  {
    label: "British Indian Ocean Territory",
    iso: "io",
  },
  {
    label: "British Virgin Islands",
    iso: "vg",
  },
  { label: "Brunei", iso: "bn" },
  { label: "Bulgaria", iso: "bg" },
  { label: "Burkina Faso", iso: "bf" },
  { label: "Burundi", iso: "bi" },
  { label: "Cambodia", iso: "kh" },
  { label: "Cameroon", iso: "cm" },
  { label: "Canada", iso: "ca" },
  { label: "Cape Verde", iso: "cv" },
  { label: "Cayman Islands", iso: "ky" },
  {
    label: "Central African Republic",
    iso: "cf",
  },
  { label: "Chad", iso: "td" },
  { label: "Chile", iso: "cl" },
  { label: "China", iso: "cn" },
  { label: "Colombia", iso: "co" },
  { label: "Comoros", iso: "km" },
  {
    label: "Congo (Brazzaville)",
    iso: "cg",
  },
  { label: "Congo (Kinshasa)", iso: "cd" },
  { label: "Cook Islands", iso: "ck" },
  { label: "Costa Rica", iso: "cr" },
  { label: "Croatia", iso: "hr" },
  { label: "Cuba", iso: "cu" },
  { label: "Curaçao", iso: "cw" },
  { label: "Cyprus", iso: "cy" },
  { label: "Czechia", iso: "cz" },
  { label: "Denmark", iso: "dk" },
  { label: "Djibouti", iso: "dj" },
  { label: "Dominica", iso: "dm" },
  { label: "Dominican Republic", iso: "do" },
  { label: "Ecuador", iso: "ec" },
  { label: "Egypt", iso: "eg" },
  { label: "El Salvador", iso: "sv" },
  { label: "England", iso: "gb-eng" },
  { label: "Equatorial Guinea", iso: "gq" },
  { label: "Eritrea", iso: "er" },
  { label: "Estonia", iso: "ee" },
  {
    label: "Eswatini (Swaziland)",
    iso: "sz",
  },
  { label: "Ethiopia", iso: "et" },
  {
    label: "Falkland Islands (Islas Malvinas)",
    iso: "fk",
  },
  { label: "Faroe Islands", iso: "fo" },
  { label: "Fiji", iso: "fj" },
  { label: "Finland", iso: "fi" },
  { label: "France", iso: "fr" },
  { label: "French Guiana", iso: "gf" },
  { label: "French Polynesia", iso: "pf" },
  {
    label: "French Southern and Antarctic Lands",
    iso: "tf",
  },
  { label: "Gabon", iso: "ga" },
  { label: "Gambia", iso: "gm" },
  { label: "Georgia", iso: "ge" },
  { label: "Germany", iso: "de" },
  { label: "Ghana", iso: "gh" },
  { label: "Gibraltar", iso: "gi" },
  { label: "Greece", iso: "gr" },
  { label: "Greenland", iso: "gl" },
  { label: "Grenada", iso: "gd" },
  { label: "Guadeloupe", iso: "gp" },
  { label: "Guam", iso: "gu" },
  { label: "Guatemala", iso: "gt" },
  { label: "Guernsey", iso: "gg" },
  { label: "Guinea", iso: "gn" },
  { label: "Guinea-Bissau", iso: "gw" },
  { label: "Guyana", iso: "gy" },
  { label: "Haiti", iso: "ht" },
  { label: "Honduras", iso: "hn" },
  { label: "Hong Kong", iso: "hk" },
  { label: "Hungary", iso: "hu" },
  { label: "Iceland", iso: "is" },
  { label: "India", iso: "in" },
  { label: "Indonesia", iso: "id" },
  { label: "Iran", iso: "ir" },
  { label: "Iraq", iso: "iq" },
  { label: "Ireland", iso: "ie" },
  { label: "Isle of Man", iso: "im" },
  { label: "Israel", iso: "il" },
  { label: "Italy", iso: "it" },
  { label: "Ivory Coast", iso: "ci" },
  { label: "Jamaica", iso: "jm" },
  { label: "Japan", iso: "jp" },
  { label: "Jersey", iso: "je" },
  { label: "Jordan", iso: "jo" },
  { label: "Kazakhstan", iso: "kz" },
  { label: "Kenya", iso: "ke" },
  { label: "Kiribati", iso: "ki" },
  { label: "Kosovo", iso: "xk" },
  { label: "Kuwait", iso: "kw" },
  { label: "Kyrgyzstan", iso: "kg" },
  { label: "Laos", iso: "la" },
  { label: "Latvia", iso: "lv" },
  { label: "Lebanon", iso: "lb" },
  { label: "Lesotho", iso: "ls" },
  { label: "Liberia", iso: "lr" },
  { label: "Libya", iso: "ly" },
  { label: "Liechtenstein", iso: "li" },
  { label: "Lithuania", iso: "lt" },
  { label: "Luxembourg", iso: "lu" },
  { label: "Macao", iso: "mo" },
  { label: "Madagascar", iso: "mg" },
  { label: "Malawi", iso: "mw" },
  { label: "Malaysia", iso: "my" },
  { label: "Maldives", iso: "mv" },
  { label: "Mali", iso: "ml" },
  { label: "Malta", iso: "mt" },
  { label: "Marshall Islands", iso: "mh" },
  { label: "Martinique", iso: "mq" },
  { label: "Mauritania", iso: "mr" },
  { label: "Mauritius", iso: "mu" },
  { label: "Mayotte", iso: "yt" },
  { label: "Mexico", iso: "mx" },
  { label: "Micronesia", iso: "fm" },
  { label: "Moldova", iso: "md" },
  { label: "Monaco", iso: "mc" },
  { label: "Mongolia", iso: "mn" },
  { label: "Montenegro", iso: "me" },
  { label: "Montserrat", iso: "ms" },
  { label: "Morocco", iso: "ma" },
  { label: "Mozambique", iso: "mz" },
  { label: "Myanmar (Burma)", iso: "mm" },
  { label: "Namibia", iso: "na" },
  { label: "Nauru", iso: "nr" },
  { label: "Nepal", iso: "np" },
  { label: "Netherlands", iso: "nl" },
  { label: "New Caledonia", iso: "nc" },
  { label: "New Zealand", iso: "nz" },
  { label: "Nicaragua", iso: "ni" },
  { label: "Niger", iso: "ne" },
  { label: "Nigeria", iso: "ng" },
  { label: "Niue", iso: "nu" },
  { label: "Norfolk Island", iso: "nf" },
  { label: "North Korea", iso: "kp" },
  { label: "North Macedonia", iso: "mk" },
  { label: "Northern Ireland", iso: "gb-nir" },
  {
    label: "Northern Mariana Islands",
    iso: "mp",
  },
  { label: "Norway", iso: "no" },
  { label: "Oman", iso: "om" },
  { label: "Pakistan", iso: "pk" },
  { label: "Palau", iso: "pw" },
  { label: "Palestine", iso: "ps" },
  { label: "Panama", iso: "pa" },
  { label: "Papua New Guinea", iso: "pg" },
  { label: "Paraguay", iso: "py" },
  { label: "Peru", iso: "pe" },
  { label: "Philippines", iso: "ph" },
  { label: "Pitcairn Islands", iso: "pn" },
  { label: "Poland", iso: "pl" },
  { label: "Portugal", iso: "pt" },
  { label: "Puerto Rico", iso: "pr" },
  { label: "Qatar", iso: "qa" },
  { label: "Romania", iso: "ro" },
  { label: "Russia", iso: "ru" },
  { label: "Rwanda", iso: "rw" },
  {
    label: "Saint Helena, Ascension and Tristan da Cunha",
    iso: "sh",
  },
  {
    label: "Saint Kitts and Nevis",
    iso: "kn",
  },
  { label: "Saint Lucia", iso: "lc" },
  {
    label: "Saint Pierre and Miquelon",
    iso: "pm",
  },
  {
    label: "Saint Vincent and the Grenadines",
    iso: "vc",
  },
  { label: "Samoa", iso: "ws" },
  { label: "San Marino", iso: "sm" },
  {
    label: "Sao Tome and Principe",
    iso: "st",
  },
  { label: "Saudi Arabia", iso: "sa" },
  { label: "Scotland", iso: "gb-sct" },
  { label: "Senegal", iso: "sn" },
  { label: "Serbia", iso: "rs" },
  { label: "Seychelles", iso: "sc" },
  { label: "Sierra Leone", iso: "sl" },
  { label: "Singapore", iso: "sg" },
  { label: "Sint Maarten", iso: "sx" },
  { label: "Slovakia", iso: "sk" },
  { label: "Slovenia", iso: "si" },
  { label: "Solomon Islands", iso: "sb" },
  { label: "Somalia", iso: "so" },
  { label: "South Africa", iso: "za" },
  { label: "South Korea", iso: "kr" },
  { label: "South Sudan", iso: "ss" },
  { label: "Spain", iso: "es" },
  { label: "Sri Lanka", iso: "lk" },
  { label: "Sudan", iso: "sd" },
  { label: "Suriname", iso: "sr" },
  {
    label: "Svalbard and Jan Mayen",
    iso: "sj",
  },
  { label: "Sweden", iso: "se" },
  { label: "Switzerland", iso: "ch" },
  { label: "Syria", iso: "sy" },
  { label: "Taiwan", iso: "tw" },
  { label: "Tajikistan", iso: "tj" },
  { label: "Tanzania", iso: "tz" },
  { label: "Thailand", iso: "th" },
  { label: "Timor-Leste", iso: "tl" },
  { label: "Togo", iso: "tg" },
  { label: "Tokelau", iso: "tk" },
  { label: "Tonga", iso: "to" },
  {
    label: "Trinidad and Tobago",
    iso: "tt",
  },
  { label: "Tunisia", iso: "tn" },
  { label: "Turkey", iso: "tr" },
  { label: "Turkmenistan", iso: "tm" },
  {
    label: "Turks and Caicos Islands",
    iso: "tc",
  },
  { label: "Tuvalu", iso: "tv" },
  { label: "Uganda", iso: "ug" },
  { label: "Ukraine", iso: "ua" },
  {
    label: "United Arab Emirates",
    iso: "ae",
  },
  { label: "United Kingdom", iso: "gb" },
  {
    label: "United States of America",
    iso: "us",
  },
  { label: "Uruguay", iso: "uy" },
  { label: "Uzbekistan", iso: "uz" },
  { label: "Vanuatu", iso: "vu" },
  {
    label: "Vatican City (Holy See)",
    iso: "va",
  },
  { label: "Venezuela", iso: "ve" },
  { label: "Vietnam", iso: "vn" },
  { label: "Wales", iso: "gb-wls" },
  { label: "Western Sahara", iso: "eh" },
  { label: "Yemen", iso: "ye" },
  { label: "Zambia", iso: "zm" },
  { label: "Zimbabwe", iso: "zw" },
];
