export type BookstoreInput = {
  name: string;
  city: string;
  country: string;
  region?: string;
};

/** Physical bookstores only — webstores and ambiguous entries excluded. */
export const BOOKSTORE_INPUT: BookstoreInput[] = [
  { name: "23 Sandy Gallery", city: "Portland", country: "United States", region: "OR" },
  { name: "Abrams Books", city: "New York", country: "United States", region: "NY" },
  { name: "Ampersand Gallery & Fine Books", city: "Portland", country: "United States", region: "OR" },
  { name: "Amstelbooks", city: "Amsterdam", country: "Netherlands" },
  { name: "Anzenberger Gallery Bookshop", city: "Vienna", country: "Austria" },
  { name: "Aperture Bookstore", city: "New York", country: "United States", region: "NY" },
  { name: "Arcana Books", city: "Culver City", country: "United States", region: "CA" },
  { name: "Athenaeum Booksellers", city: "Amsterdam", country: "Netherlands" },
  { name: "Bildband Berlin", city: "Berlin", country: "Germany" },
  { name: "Boekie Woekie", city: "Amsterdam", country: "Netherlands" },
  { name: "Book Alley", city: "Pasadena", country: "United States", region: "CA" },
  { name: "Book of Days", city: "Osaka", country: "Japan" },
  { name: "Book Soup", city: "West Hollywood", country: "United States", region: "CA" },
  { name: "Books & Books", city: "Miami", country: "United States", region: "FL" },
  { name: "Buecherbogen", city: "Berlin", country: "Germany" },
  { name: "Claire de Rouen", city: "London", country: "United Kingdom" },
  { name: "Carpe Diem", city: "Monterey", country: "United States", region: "CA" },
  { name: "Central Booking", city: "New York", country: "United States", region: "NY" },
  { name: "Chloé et Denis Ozanne", city: "Paris", country: "France" },
  { name: "Dalpine", city: "Madrid", country: "Spain" },
  { name: "Dispara Xestión Cultural", city: "Pontevedra", country: "Spain" },
  { name: "Deichtorhallen Book Shop", city: "Hamburg", country: "Germany" },
  { name: "Dia Books", city: "Beacon", country: "United States", region: "NY" },
  { name: "Donlon Books", city: "London", country: "United Kingdom" },
  { name: "Florence Loewy Book by Artists", city: "Paris", country: "France" },
  { name: "Flying Books", city: "Tokyo", country: "Japan" },
  { name: "Fragment", city: "Copenhagen", country: "Denmark" },
  { name: "Grant Librería", city: "Madrid", country: "Spain" },
  { name: "Harper's Books", city: "East Hampton", country: "United States", region: "NY" },
  { name: "Hennessey + Ingalls", city: "Los Angeles", country: "United States", region: "CA" },
  { name: "Huis Marseille", city: "Amsterdam", country: "Netherlands" },
  { name: "Hochparterre Bücher", city: "Zurich", country: "Switzerland" },
  { name: "Hors Format Bookstore", city: "Brussels", country: "Belgium" },
  { name: "International Center of Photography", city: "New York", country: "United States", region: "NY" },
  { name: "Inc-Livros Edições de Autor", city: "Porto", country: "Portugal" },
  { name: "Junku.fr", city: "Paris", country: "France" },
  { name: "Jeu de Paume", city: "Paris", country: "France" },
  { name: "Karma Books", city: "New York", country: "United States", region: "NY" },
  { name: "Kominek Gallery", city: "Berlin", country: "Germany" },
  { name: "Bokhandeln Konstig", city: "Stockholm", country: "Sweden" },
  { name: "La Chambre Claire", city: "Paris", country: "France" },
  { name: "La Fabrica", city: "Madrid", country: "Spain" },
  { name: "Le BAL", city: "Paris", country: "France" },
  { name: "Le Mur", city: "Madrid", country: "Spain" },
  { name: "Le Plac'Art Photo", city: "Paris", country: "France" },
  { name: "LeadApron", city: "Los Angeles", country: "United States", region: "CA" },
  { name: "Librairie Photographique", city: "Paris", country: "France" },
  { name: "Mecanic", city: "Barcelona", country: "Spain" },
  { name: "MiCamera", city: "Milan", country: "Italy" },
  { name: "Mona Lisait", city: "Paris", country: "France" },
  { name: "Monograph Bookwerks", city: "Portland", country: "United States", region: "OR" },
  { name: "Perimeter Books", city: "Melbourne", country: "Australia" },
  { name: "PH", city: "Tokyo", country: "Japan" },
  { name: "Photobooks International", city: "Los Angeles", country: "United States", region: "CA" },
  { name: "photo-eye", city: "Santa Fe", country: "United States", region: "NM" },
  { name: "The Photographers' Gallery Bookshop", city: "London", country: "United Kingdom" },
  { name: "PhotoQ Bookshop", city: "Amsterdam", country: "Netherlands" },
  { name: "Powell's Books", city: "Portland", country: "United States", region: "OR" },
  { name: "Printed Matter", city: "New York", country: "United States", region: "NY" },
  { name: "Purr Libros", city: "Buenos Aires", country: "Argentina" },
  { name: "RVB Books", city: "Paris", country: "France" },
  { name: "Setanta Books", city: "London", country: "United Kingdom" },
  { name: "Spaces Corners", city: "Pittsburgh", country: "United States", region: "PA" },
  { name: "Strand Books", city: "New York", country: "United States", region: "NY" },
  { name: "STET Livros e Fotografias", city: "Lisbon", country: "Portugal" },
  { name: "The Library Project", city: "Dublin", country: "Ireland" },
  { name: "Ti Pi Tin", city: "London", country: "United Kingdom" },
  { name: "Tipi Bookshop", city: "Brussels", country: "Belgium" },
  { name: "Vincent Borrelli, Bookseller", city: "Albuquerque", country: "United States", region: "NM" },
  { name: "Wessel & Lieberman Booksellers", city: "Seattle", country: "United States", region: "WA" },
  { name: "XYZ Books", city: "Lisbon", country: "Portugal" },
];
