#!/usr/bin/env tsx
/**
 * Weekly Code Audit Script
 * Runs a comprehensive code audit using Cursor AI and saves the results
 */

import { Agent } from "@cursor/sdk";
import { writeFile } from "fs/promises";
import { join } from "path";

const CURSOR_API_KEY = process.env.CURSOR_API_KEY;

if (!CURSOR_API_KEY) {
  console.error("Error: CURSOR_API_KEY environment variable is required");
  console.error("Get your API key from: https://cursor.com/dashboard/integrations");
  process.exit(1);
}

const AUDIT_PROMPT = `Please perform a comprehensive code audit of this project. Focus on:

1. **Code Quality & Architecture**
   - Identify code smells, anti-patterns, or technical debt
   - Check for inconsistent patterns or architectural issues
   - Look for overly complex functions or files

2. **Performance & Optimization**
   - Identify potential performance bottlenecks
   - Check for inefficient database queries or N+1 problems
   - Look for unnecessary re-renders or computation

3. **Security**
   - Check for potential security vulnerabilities
   - Verify proper input validation and sanitization
   - Look for exposed secrets or sensitive data

4. **Best Practices**
   - Check TypeScript usage (proper types, no 'any' abuse)
   - Verify error handling patterns
   - Check for proper async/await usage

5. **Maintainability**
   - Identify areas lacking documentation
   - Check for duplicated code
   - Look for overly coupled components

Format the audit as a structured markdown document with:
- Executive summary
- Detailed findings by category
- Specific file/line references where applicable
- Severity ratings (Critical/High/Medium/Low)
- Recommended actions

Focus on actionable insights rather than minor style issues.`;

async function runWeeklyAudit() {
  const timestamp = new Date().toISOString().split("T")[0];
  const outputPath = join(process.cwd(), `AUDIT_${timestamp}.md`);

  console.log(`\n🔍 Starting weekly code audit...`);
  console.log(`📅 Date: ${timestamp}`);
  console.log(`📁 Project: ${process.cwd()}\n`);

  try {
    const result = await Agent.prompt(AUDIT_PROMPT, {
      apiKey: CURSOR_API_KEY,
      model: { id: "composer-2.5" },
      local: { cwd: process.cwd() },
    });

    if (result.status === "error") {
      console.error(`❌ Audit failed with status: ${result.status}`);
      console.error(`Run ID: ${result.id}`);
      process.exit(2);
    }

    if (result.status === "finished") {
      // Extract the audit report from the result
      const auditReport = result.result || "No audit content generated.";
      
      // Create a formatted audit document
      const fullReport = `# Code Audit Report
**Date:** ${new Date().toISOString()}
**Project:** photobookers
**Generated by:** Cursor AI (Automated Weekly Audit)

---

${auditReport}

---

*This audit was automatically generated by the weekly audit script.*
*Run ID: ${result.id}*
`;

      await writeFile(outputPath, fullReport, "utf-8");

      console.log(`✅ Audit completed successfully!`);
      console.log(`📄 Report saved to: ${outputPath}`);
      console.log(`🔗 Run ID: ${result.id}`);
      
      // Optionally, you could also:
      // - Send the report via email
      // - Post to Slack
      // - Create a GitHub issue
      // - Commit the report to git
      
      process.exit(0);
    } else {
      console.warn(`⚠️  Audit ended with status: ${result.status}`);
      process.exit(1);
    }
  } catch (err) {
    if (err instanceof Error && err.constructor.name === "CursorAgentError") {
      const error = err as any;
      console.error(`❌ Startup failed: ${error.message}`);
      console.error(`🔄 Retryable: ${error.isRetryable}`);
      process.exit(1);
    }
    throw err;
  }
}

runWeeklyAudit();
