// Auto-generated by hono-fsr, do not edit.
// @ts-nocheck

import type { Manifest } from "hono-fsr";

import * as m0 from "./fs-routes/dashboard/+middleware";
import * as m1 from "./fs-routes/dashboard/admin/+middleware";
import * as m2 from "./fs-routes/(app)/about";
import * as m3 from "./fs-routes/(app)/artist-of-the-week";
import * as m4 from "./fs-routes/(app)/artists";
import * as m5 from "./fs-routes/(app)/book-of-the-day";
import * as m6 from "./fs-routes/(app)/books";
import * as m7 from "./fs-routes/(app)/contact";
import * as m8 from "./fs-routes/(app)/creators";
import * as m9 from "./fs-routes/(app)/fairs";
import * as m10 from "./fs-routes/(app)/featured";
import * as m11 from "./fs-routes/(app)/feed";
import * as m12 from "./fs-routes/(app)/followed-creators";
import * as m13 from "./fs-routes/(app)/fragments/creators-slider";
import * as m14 from "./fs-routes/(app)/fragments/fairs";
import * as m15 from "./fs-routes/(app)/fragments/latest-books";
import * as m16 from "./fs-routes/(app)/fragments/stats";
import * as m17 from "./fs-routes/(app)/fragments/stores";
import * as m18 from "./fs-routes/(app)/index";
import * as m19 from "./fs-routes/(app)/interviews/index";
import * as m20 from "./fs-routes/(app)/library";
import * as m21 from "./fs-routes/(app)/links";
import * as m22 from "./fs-routes/(app)/magazine/index";
import * as m23 from "./fs-routes/(app)/magazine/on-the-sidewalk";
import * as m24 from "./fs-routes/(app)/messages";
import * as m25 from "./fs-routes/(app)/newsletter";
import * as m26 from "./fs-routes/(app)/privacy";
import * as m27 from "./fs-routes/(app)/publisher-of-the-week";
import * as m28 from "./fs-routes/(app)/publishers";
import * as m29 from "./fs-routes/(app)/search/mobile";
import * as m30 from "./fs-routes/(app)/search/results";
import * as m31 from "./fs-routes/(app)/search";
import * as m32 from "./fs-routes/(app)/stores";
import * as m33 from "./fs-routes/(app)/terms";
import * as m34 from "./fs-routes/(app)/this-week";
import * as m35 from "./fs-routes/api/activity/stream";
import * as m36 from "./fs-routes/api/newsletter";
import * as m37 from "./fs-routes/api/project-summary.txt";
import * as m38 from "./fs-routes/auth/accounts";
import * as m39 from "./fs-routes/auth/callback";
import * as m40 from "./fs-routes/auth/force-reset-password";
import * as m41 from "./fs-routes/auth/forgot-password";
import * as m42 from "./fs-routes/auth/login";
import * as m43 from "./fs-routes/auth/logout";
import * as m44 from "./fs-routes/auth/register-creator";
import * as m45 from "./fs-routes/auth/register-fan";
import * as m46 from "./fs-routes/auth/register";
import * as m47 from "./fs-routes/auth/resend-verification";
import * as m48 from "./fs-routes/auth/reset-password";
import * as m49 from "./fs-routes/auth/set-session";
import * as m50 from "./fs-routes/auth/update-password";
import * as m51 from "./fs-routes/auth/validate/display-name";
import * as m52 from "./fs-routes/auth/validate/email";
import * as m53 from "./fs-routes/auth/validate/website";
import * as m54 from "./fs-routes/claims/complete";
import * as m55 from "./fs-routes/dashboard/admin/analytics/fans/index";
import * as m56 from "./fs-routes/dashboard/admin/analytics/index";
import * as m57 from "./fs-routes/dashboard/admin/analytics/verified-creators/index";
import * as m58 from "./fs-routes/dashboard/admin/books/books-table-filter";
import * as m59 from "./fs-routes/dashboard/admin/books/create";
import * as m60 from "./fs-routes/dashboard/admin/books/index";
import * as m61 from "./fs-routes/dashboard/admin/claims/index";
import * as m62 from "./fs-routes/dashboard/admin/claims/pending-count";
import * as m63 from "./fs-routes/dashboard/admin/creators/create";
import * as m64 from "./fs-routes/dashboard/admin/creators/creators-table-filter";
import * as m65 from "./fs-routes/dashboard/admin/creators/index";
import * as m66 from "./fs-routes/dashboard/admin/fairs/create";
import * as m67 from "./fs-routes/dashboard/admin/fairs/index";
import * as m68 from "./fs-routes/dashboard/admin/interviews/index";
import * as m69 from "./fs-routes/dashboard/admin/interviews/interviews-table-filter";
import * as m70 from "./fs-routes/dashboard/admin/notifications/index";
import * as m71 from "./fs-routes/dashboard/admin/notifications/read-all";
import * as m72 from "./fs-routes/dashboard/admin/notifications/unread-count";
import * as m73 from "./fs-routes/dashboard/admin/planner/artist-of-the-week/send-creator-email";
import * as m74 from "./fs-routes/dashboard/admin/planner/artist-of-the-week/set-send-email";
import * as m75 from "./fs-routes/dashboard/admin/planner/book-of-the-day/send-creator-email";
import * as m76 from "./fs-routes/dashboard/admin/planner/book-of-the-day/set-send-email";
import * as m77 from "./fs-routes/dashboard/admin/planner/index";
import * as m78 from "./fs-routes/dashboard/admin/planner/newsletters/index";
import * as m79 from "./fs-routes/dashboard/admin/planner/publisher-of-the-week/send-creator-email";
import * as m80 from "./fs-routes/dashboard/admin/planner/publisher-of-the-week/set-send-email";
import * as m81 from "./fs-routes/dashboard/admin/planner/spotlight-blurb/generate";
import * as m82 from "./fs-routes/dashboard/admin/planner/spotlight-blurb/prepare";
import * as m83 from "./fs-routes/dashboard/admin/stores/create";
import * as m84 from "./fs-routes/dashboard/admin/stores/index";
import * as m85 from "./fs-routes/dashboard/admin/users/create";
import * as m86 from "./fs-routes/dashboard/admin/users/delete-multiple";
import * as m87 from "./fs-routes/dashboard/admin/users/index";
import * as m88 from "./fs-routes/dashboard/analytics/index";
import * as m89 from "./fs-routes/dashboard/books/import/images/upload";
import * as m90 from "./fs-routes/dashboard/books/import/images";
import * as m91 from "./fs-routes/dashboard/books/import/template";
import * as m92 from "./fs-routes/dashboard/books/import";
import * as m93 from "./fs-routes/dashboard/books/index";
import * as m94 from "./fs-routes/dashboard/books/new";
import * as m95 from "./fs-routes/dashboard/books/reorder";
import * as m96 from "./fs-routes/dashboard/index";
import * as m97 from "./fs-routes/dashboard/messages/index";
import * as m98 from "./fs-routes/hyperview/(app)/about";
import * as m99 from "./fs-routes/hyperview/(app)/accounts";
import * as m100 from "./fs-routes/hyperview/(app)/artist-of-the-week";
import * as m101 from "./fs-routes/hyperview/(app)/auth-modal";
import * as m102 from "./fs-routes/hyperview/(app)/book-of-the-day";
import * as m103 from "./fs-routes/hyperview/(app)/books";
import * as m104 from "./fs-routes/hyperview/(app)/creators/tab/all";
import * as m105 from "./fs-routes/hyperview/(app)/creators/tab/artists";
import * as m106 from "./fs-routes/hyperview/(app)/creators/tab/following";
import * as m107 from "./fs-routes/hyperview/(app)/creators/tab/publishers";
import * as m108 from "./fs-routes/hyperview/(app)/creators";
import * as m109 from "./fs-routes/hyperview/(app)/fairs/tab/current";
import * as m110 from "./fs-routes/hyperview/(app)/fairs/tab/past";
import * as m111 from "./fs-routes/hyperview/(app)/fairs/tab/upcoming";
import * as m112 from "./fs-routes/hyperview/(app)/fairs";
import * as m113 from "./fs-routes/hyperview/(app)/favorites";
import * as m114 from "./fs-routes/hyperview/(app)/featured/tab/fairs";
import * as m115 from "./fs-routes/hyperview/(app)/featured/tab/feed";
import * as m116 from "./fs-routes/hyperview/(app)/featured/tab/groups";
import * as m117 from "./fs-routes/hyperview/(app)/featured/tab/home-content";
import * as m118 from "./fs-routes/hyperview/(app)/featured/tab/interviews";
import * as m119 from "./fs-routes/hyperview/(app)/featured/tab/latest-books";
import * as m120 from "./fs-routes/hyperview/(app)/featured/tab/messages";
import * as m121 from "./fs-routes/hyperview/(app)/featured/tab/stores";
import * as m122 from "./fs-routes/hyperview/(app)/featured/tab/trending-creators";
import * as m123 from "./fs-routes/hyperview/(app)/featured";
import * as m124 from "./fs-routes/hyperview/(app)/interviews";
import * as m125 from "./fs-routes/hyperview/(app)/login";
import * as m126 from "./fs-routes/hyperview/(app)/logout";
import * as m127 from "./fs-routes/hyperview/(app)/messages";
import * as m128 from "./fs-routes/hyperview/(app)/privacy";
import * as m129 from "./fs-routes/hyperview/(app)/publisher-of-the-week";
import * as m130 from "./fs-routes/hyperview/(app)/register";
import * as m131 from "./fs-routes/hyperview/(app)/search";
import * as m132 from "./fs-routes/hyperview/(app)/settings/tab/privacy";
import * as m133 from "./fs-routes/hyperview/(app)/settings/tab/terms";
import * as m134 from "./fs-routes/hyperview/(app)/stores";
import * as m135 from "./fs-routes/hyperview/(app)/terms";
import * as m136 from "./fs-routes/hyperview/(app)/this-week";
import * as m137 from "./fs-routes/hyperview/+layout";
import * as m138 from "./fs-routes/hyperview/index";
import * as m139 from "./fs-routes/jobs/cron/botd-advance-notification-emails";
import * as m140 from "./fs-routes/jobs/cron/botd-feature-day-emails";
import * as m141 from "./fs-routes/jobs/cron/ceo-metrics-email";
import * as m142 from "./fs-routes/jobs/cron/creator-analytics-digest";
import * as m143 from "./fs-routes/jobs/cron/creator-milestone-emails";
import * as m144 from "./fs-routes/jobs/cron/creator-profile-share-emails";
import * as m145 from "./fs-routes/jobs/cron/daily-botd-instagram";
import * as m146 from "./fs-routes/jobs/cron/daily-product-digest";
import * as m147 from "./fs-routes/jobs/cron/instagram-prep-reminder-email";
import * as m148 from "./fs-routes/jobs/cron/interview-reminder-emails";
import * as m149 from "./fs-routes/jobs/cron/notify-followers-new-books";
import * as m150 from "./fs-routes/jobs/cron/notify-followers-new-posts";
import * as m151 from "./fs-routes/jobs/cron/planner-content-preview-email";
import * as m152 from "./fs-routes/jobs/cron/spotlight-creator-emails";
import * as m153 from "./fs-routes/jobs/cron/stub-outreach-emails";
import * as m154 from "./fs-routes/jobs/cron/verification-feedback-emails";
import * as m155 from "./fs-routes/jobs/cron/verified-creator-instagram";
import * as m156 from "./fs-routes/jobs/cron/weekly-botd-newsletter";
import * as m157 from "./fs-routes/jobs/cron/weekly-trending-instagram";
import * as m158 from "./fs-routes/robots.txt";
import * as m159 from "./fs-routes/sitemap.xml";
import * as m160 from "./fs-routes/(app)/artist-of-the-week/[week]";
import * as m161 from "./fs-routes/(app)/book-of-the-day/[date]";
import * as m162 from "./fs-routes/(app)/books/[slug]";
import * as m163 from "./fs-routes/(app)/books/preview/[slug]";
import * as m164 from "./fs-routes/(app)/books/tags/[tag]";
import * as m165 from "./fs-routes/(app)/creators/[slug]";
import * as m166 from "./fs-routes/(app)/fairs/[slug]";
import * as m167 from "./fs-routes/(app)/fragments/related-books/[slug]";
import * as m168 from "./fs-routes/(app)/interviews/[tokenId]/opt-out-reminders";
import * as m169 from "./fs-routes/(app)/interviews/[tokenId]";
import * as m170 from "./fs-routes/(app)/interviews/view/[slug]";
import * as m171 from "./fs-routes/(app)/out/[slug]";
import * as m172 from "./fs-routes/(app)/publisher-of-the-week/[week]";
import * as m173 from "./fs-routes/(app)/stores/[slug]";
import * as m174 from "./fs-routes/(app)/users/[userId]/update";
import * as m175 from "./fs-routes/api/books/[bookId]/collect";
import * as m176 from "./fs-routes/api/books/[bookId]/comments/[commentId]";
import * as m177 from "./fs-routes/api/books/[bookId]/comments";
import * as m178 from "./fs-routes/api/books/[bookId]/like";
import * as m179 from "./fs-routes/api/books/[bookId]/wishlist";
import * as m180 from "./fs-routes/api/creators/[creatorId]/follow";
import * as m181 from "./fs-routes/api/fairs/[fairId]/attend";
import * as m182 from "./fs-routes/api/users/[userId]/profile-image";
import * as m183 from "./fs-routes/claims/[creatorId]/index";
import * as m184 from "./fs-routes/claims/[creatorId]/register-and-claim";
import * as m185 from "./fs-routes/claims/[creatorId]/start/signup";
import * as m186 from "./fs-routes/claims/[creatorId]/start";
import * as m187 from "./fs-routes/claims/[creatorId]";
import * as m188 from "./fs-routes/dashboard/admin/books/[bookId]/approve";
import * as m189 from "./fs-routes/dashboard/admin/books/[bookId]/reject";
import * as m190 from "./fs-routes/dashboard/admin/books/[bookId]";
import * as m191 from "./fs-routes/dashboard/admin/claims/[claimId]/approve";
import * as m192 from "./fs-routes/dashboard/admin/claims/[claimId]/reject";
import * as m193 from "./fs-routes/dashboard/admin/creators/[creatorId]/delete";
import * as m194 from "./fs-routes/dashboard/admin/creators/[creatorId]/remove-owner";
import * as m195 from "./fs-routes/dashboard/admin/creators/[creatorId]/send-interview";
import * as m196 from "./fs-routes/dashboard/admin/creators/[creatorId]/send-welcome-email";
import * as m197 from "./fs-routes/dashboard/admin/creators/[creatorId]/toggle-stub-outreach-opt-out";
import * as m198 from "./fs-routes/dashboard/admin/creators/[creatorId]";
import * as m199 from "./fs-routes/dashboard/admin/creators/assign-owner/[creatorId]";
import * as m200 from "./fs-routes/dashboard/admin/creators/assign-owner-content/[creatorId]";
import * as m201 from "./fs-routes/dashboard/admin/fairs/[fairId]/approve";
import * as m202 from "./fs-routes/dashboard/admin/fairs/[fairId]/attendees/[attendeeId]/approve";
import * as m203 from "./fs-routes/dashboard/admin/fairs/[fairId]/attendees/[attendeeId]/reject";
import * as m204 from "./fs-routes/dashboard/admin/fairs/[fairId]/attendees";
import * as m205 from "./fs-routes/dashboard/admin/fairs/[fairId]/reject";
import * as m206 from "./fs-routes/dashboard/admin/fairs/[fairId]";
import * as m207 from "./fs-routes/dashboard/admin/interviews/[interviewId]";
import * as m208 from "./fs-routes/dashboard/admin/notifications/[notificationId]/read";
import * as m209 from "./fs-routes/dashboard/admin/planner/artist-of-the-week/[week]/create";
import * as m210 from "./fs-routes/dashboard/admin/planner/artist-of-the-week/[week]";
import * as m211 from "./fs-routes/dashboard/admin/planner/book-of-the-day/[date]/create";
import * as m212 from "./fs-routes/dashboard/admin/planner/book-of-the-day/[date]";
import * as m213 from "./fs-routes/dashboard/admin/planner/book-of-the-day/[week]/randomize";
import * as m214 from "./fs-routes/dashboard/admin/planner/creators/[creatorId]/edit-email";
import * as m215 from "./fs-routes/dashboard/admin/planner/featured-hero/[week]/prepare";
import * as m216 from "./fs-routes/dashboard/admin/planner/instagram/[week]/clear";
import * as m217 from "./fs-routes/dashboard/admin/planner/instagram/[week]/prepare";
import * as m218 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/delete";
import * as m219 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/mark-sent";
import * as m220 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/regenerate";
import * as m221 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/save";
import * as m222 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/send-brevo-test";
import * as m223 from "./fs-routes/dashboard/admin/planner/newsletters/[campaignId]/send-brevo";
import * as m224 from "./fs-routes/dashboard/admin/planner/publisher-of-the-week/[week]/create";
import * as m225 from "./fs-routes/dashboard/admin/planner/publisher-of-the-week/[week]";
import * as m226 from "./fs-routes/dashboard/admin/planner/spotlight-copy/[week]/generate";
import * as m227 from "./fs-routes/dashboard/admin/planner/spotlight-copy/[week]/prepare";
import * as m228 from "./fs-routes/dashboard/admin/stores/[storeId]/approve";
import * as m229 from "./fs-routes/dashboard/admin/stores/[storeId]/reject";
import * as m230 from "./fs-routes/dashboard/admin/stores/[storeId]";
import * as m231 from "./fs-routes/dashboard/admin/users/[userId]/reset-password";
import * as m232 from "./fs-routes/dashboard/admin/users/[userId]";
import * as m233 from "./fs-routes/dashboard/books/[bookId]/publisher";
import * as m234 from "./fs-routes/dashboard/books/[bookId]/resubmit";
import * as m235 from "./fs-routes/dashboard/books/[bookId]";
import * as m236 from "./fs-routes/dashboard/creators/[creatorId]";
import * as m237 from "./fs-routes/dashboard/images/books/[bookId]/cover";
import * as m238 from "./fs-routes/dashboard/images/books/[bookId]/gallery";
import * as m239 from "./fs-routes/dashboard/images/creators/[creatorId]/banner";
import * as m240 from "./fs-routes/dashboard/images/creators/[creatorId]/cover";
import * as m241 from "./fs-routes/dashboard/images/fairs/[fairId]/banner";
import * as m242 from "./fs-routes/dashboard/images/fairs/[fairId]/cover";
import * as m243 from "./fs-routes/dashboard/images/stores/[storeId]/cover";
import * as m244 from "./fs-routes/dashboard/images/users/[userId]/profile";
import * as m245 from "./fs-routes/dashboard/messages/[creatorId]/[messageId]";
import * as m246 from "./fs-routes/dashboard/messages/[creatorId]";
import * as m247 from "./fs-routes/hyperview/(app)/artist-of-the-week/[week]";
import * as m248 from "./fs-routes/hyperview/(app)/book-of-the-day/[date]";
import * as m249 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/artist-books/[artistId]";
import * as m250 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/artist";
import * as m251 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/book-content";
import * as m252 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/book";
import * as m253 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/comments";
import * as m254 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/publisher-books/[publisherId]";
import * as m255 from "./fs-routes/hyperview/(app)/books/[bookId]/tab/publisher";
import * as m256 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/about";
import * as m257 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/artists";
import * as m258 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/books-content";
import * as m259 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/books";
import * as m260 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/messages";
import * as m261 from "./fs-routes/hyperview/(app)/creators/[creatorId]/tab/publishers";
import * as m262 from "./fs-routes/hyperview/(app)/creators/[id]/tab/books-content";
import * as m263 from "./fs-routes/hyperview/(app)/fairs/[slug]/attending-creators";
import * as m264 from "./fs-routes/hyperview/(app)/fairs/[slug]";
import * as m265 from "./fs-routes/hyperview/(app)/interviews/view/[slug]";
import * as m266 from "./fs-routes/hyperview/(app)/publisher-of-the-week/[week]";
import * as m267 from "./fs-routes/hyperview/(app)/stores/[slug]";
import * as m268 from "./fs-routes/hyperview/(app)/tags/[tag]";

export const manifest: Manifest = [
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/+middleware.ts",
    urlPath: "/dashboard",
    type: "middleware",
    precedence: 0,
    module: m0
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/+middleware.ts",
    urlPath: "/dashboard/admin",
    type: "middleware",
    precedence: 0,
    module: m1
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/about.tsx",
    urlPath: "/about",
    type: "handler",
    precedence: 1,
    module: m2
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/artist-of-the-week.tsx",
    urlPath: "/artist-of-the-week",
    type: "handler",
    precedence: 1,
    module: m3
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/artists.tsx",
    urlPath: "/artists",
    type: "handler",
    precedence: 1,
    module: m4
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/book-of-the-day.tsx",
    urlPath: "/book-of-the-day",
    type: "handler",
    precedence: 1,
    module: m5
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/books.tsx",
    urlPath: "/books",
    type: "handler",
    precedence: 1,
    module: m6
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/contact.tsx",
    urlPath: "/contact",
    type: "handler",
    precedence: 1,
    module: m7
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/creators.tsx",
    urlPath: "/creators",
    type: "handler",
    precedence: 1,
    module: m8
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fairs.tsx",
    urlPath: "/fairs",
    type: "handler",
    precedence: 1,
    module: m9
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/featured.tsx",
    urlPath: "/featured",
    type: "handler",
    precedence: 1,
    module: m10
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/feed.tsx",
    urlPath: "/feed",
    type: "handler",
    precedence: 1,
    module: m11
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/followed-creators.tsx",
    urlPath: "/followed-creators",
    type: "handler",
    precedence: 1,
    module: m12
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/creators-slider.tsx",
    urlPath: "/fragments/creators-slider",
    type: "handler",
    precedence: 1,
    module: m13
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/fairs.tsx",
    urlPath: "/fragments/fairs",
    type: "handler",
    precedence: 1,
    module: m14
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/latest-books.tsx",
    urlPath: "/fragments/latest-books",
    type: "handler",
    precedence: 1,
    module: m15
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/stats.tsx",
    urlPath: "/fragments/stats",
    type: "handler",
    precedence: 1,
    module: m16
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/stores.tsx",
    urlPath: "/fragments/stores",
    type: "handler",
    precedence: 1,
    module: m17
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/index.tsx",
    urlPath: "/",
    type: "handler",
    precedence: 1,
    module: m18
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/interviews/index.tsx",
    urlPath: "/interviews",
    type: "handler",
    precedence: 1,
    module: m19
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/library.tsx",
    urlPath: "/library",
    type: "handler",
    precedence: 1,
    module: m20
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/links.tsx",
    urlPath: "/links",
    type: "handler",
    precedence: 1,
    module: m21
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/magazine/index.tsx",
    urlPath: "/magazine",
    type: "handler",
    precedence: 1,
    module: m22
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/magazine/on-the-sidewalk.tsx",
    urlPath: "/magazine/on-the-sidewalk",
    type: "handler",
    precedence: 1,
    module: m23
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/messages.tsx",
    urlPath: "/messages",
    type: "handler",
    precedence: 1,
    module: m24
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/newsletter.tsx",
    urlPath: "/newsletter",
    type: "handler",
    precedence: 1,
    module: m25
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/privacy.tsx",
    urlPath: "/privacy",
    type: "handler",
    precedence: 1,
    module: m26
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/publisher-of-the-week.tsx",
    urlPath: "/publisher-of-the-week",
    type: "handler",
    precedence: 1,
    module: m27
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/publishers.tsx",
    urlPath: "/publishers",
    type: "handler",
    precedence: 1,
    module: m28
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/search/mobile.tsx",
    urlPath: "/search/mobile",
    type: "handler",
    precedence: 1,
    module: m29
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/search/results.tsx",
    urlPath: "/search/results",
    type: "handler",
    precedence: 1,
    module: m30
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/search.tsx",
    urlPath: "/search",
    type: "handler",
    precedence: 1,
    module: m31
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/stores.tsx",
    urlPath: "/stores",
    type: "handler",
    precedence: 1,
    module: m32
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/terms.tsx",
    urlPath: "/terms",
    type: "handler",
    precedence: 1,
    module: m33
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/this-week.tsx",
    urlPath: "/this-week",
    type: "handler",
    precedence: 1,
    module: m34
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/activity/stream.tsx",
    urlPath: "/api/activity/stream",
    type: "handler",
    precedence: 1,
    module: m35
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/newsletter.tsx",
    urlPath: "/api/newsletter",
    type: "handler",
    precedence: 1,
    module: m36
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/project-summary.txt.tsx",
    urlPath: "/api/project-summary.txt",
    type: "handler",
    precedence: 1,
    module: m37
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/accounts.tsx",
    urlPath: "/auth/accounts",
    type: "handler",
    precedence: 1,
    module: m38
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/callback.tsx",
    urlPath: "/auth/callback",
    type: "handler",
    precedence: 1,
    module: m39
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/force-reset-password.tsx",
    urlPath: "/auth/force-reset-password",
    type: "handler",
    precedence: 1,
    module: m40
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/forgot-password.tsx",
    urlPath: "/auth/forgot-password",
    type: "handler",
    precedence: 1,
    module: m41
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/login.tsx",
    urlPath: "/auth/login",
    type: "handler",
    precedence: 1,
    module: m42
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/logout.tsx",
    urlPath: "/auth/logout",
    type: "handler",
    precedence: 1,
    module: m43
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/register-creator.tsx",
    urlPath: "/auth/register-creator",
    type: "handler",
    precedence: 1,
    module: m44
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/register-fan.tsx",
    urlPath: "/auth/register-fan",
    type: "handler",
    precedence: 1,
    module: m45
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/register.tsx",
    urlPath: "/auth/register",
    type: "handler",
    precedence: 1,
    module: m46
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/resend-verification.tsx",
    urlPath: "/auth/resend-verification",
    type: "handler",
    precedence: 1,
    module: m47
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/reset-password.tsx",
    urlPath: "/auth/reset-password",
    type: "handler",
    precedence: 1,
    module: m48
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/set-session.tsx",
    urlPath: "/auth/set-session",
    type: "handler",
    precedence: 1,
    module: m49
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/update-password.tsx",
    urlPath: "/auth/update-password",
    type: "handler",
    precedence: 1,
    module: m50
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/validate/display-name.tsx",
    urlPath: "/auth/validate/display-name",
    type: "handler",
    precedence: 1,
    module: m51
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/validate/email.tsx",
    urlPath: "/auth/validate/email",
    type: "handler",
    precedence: 1,
    module: m52
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/auth/validate/website.tsx",
    urlPath: "/auth/validate/website",
    type: "handler",
    precedence: 1,
    module: m53
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/complete.tsx",
    urlPath: "/claims/complete",
    type: "handler",
    precedence: 1,
    module: m54
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/analytics/fans/index.tsx",
    urlPath: "/dashboard/admin/analytics/fans",
    type: "handler",
    precedence: 1,
    module: m55
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/analytics/index.tsx",
    urlPath: "/dashboard/admin/analytics",
    type: "handler",
    precedence: 1,
    module: m56
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/analytics/verified-creators/index.tsx",
    urlPath: "/dashboard/admin/analytics/verified-creators",
    type: "handler",
    precedence: 1,
    module: m57
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/books-table-filter.tsx",
    urlPath: "/dashboard/admin/books/books-table-filter",
    type: "handler",
    precedence: 1,
    module: m58
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/create.tsx",
    urlPath: "/dashboard/admin/books/create",
    type: "handler",
    precedence: 1,
    module: m59
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/index.tsx",
    urlPath: "/dashboard/admin/books",
    type: "handler",
    precedence: 1,
    module: m60
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/claims/index.tsx",
    urlPath: "/dashboard/admin/claims",
    type: "handler",
    precedence: 1,
    module: m61
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/claims/pending-count.tsx",
    urlPath: "/dashboard/admin/claims/pending-count",
    type: "handler",
    precedence: 1,
    module: m62
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/create.tsx",
    urlPath: "/dashboard/admin/creators/create",
    type: "handler",
    precedence: 1,
    module: m63
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/creators-table-filter.tsx",
    urlPath: "/dashboard/admin/creators/creators-table-filter",
    type: "handler",
    precedence: 1,
    module: m64
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/index.tsx",
    urlPath: "/dashboard/admin/creators",
    type: "handler",
    precedence: 1,
    module: m65
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/create.tsx",
    urlPath: "/dashboard/admin/fairs/create",
    type: "handler",
    precedence: 1,
    module: m66
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/index.tsx",
    urlPath: "/dashboard/admin/fairs",
    type: "handler",
    precedence: 1,
    module: m67
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/interviews/index.tsx",
    urlPath: "/dashboard/admin/interviews",
    type: "handler",
    precedence: 1,
    module: m68
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/interviews/interviews-table-filter.tsx",
    urlPath: "/dashboard/admin/interviews/interviews-table-filter",
    type: "handler",
    precedence: 1,
    module: m69
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/notifications/index.tsx",
    urlPath: "/dashboard/admin/notifications",
    type: "handler",
    precedence: 1,
    module: m70
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/notifications/read-all.tsx",
    urlPath: "/dashboard/admin/notifications/read-all",
    type: "handler",
    precedence: 1,
    module: m71
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/notifications/unread-count.tsx",
    urlPath: "/dashboard/admin/notifications/unread-count",
    type: "handler",
    precedence: 1,
    module: m72
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/artist-of-the-week/send-creator-email.tsx",
    urlPath: "/dashboard/admin/planner/artist-of-the-week/send-creator-email",
    type: "handler",
    precedence: 1,
    module: m73
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/artist-of-the-week/set-send-email.tsx",
    urlPath: "/dashboard/admin/planner/artist-of-the-week/set-send-email",
    type: "handler",
    precedence: 1,
    module: m74
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/book-of-the-day/send-creator-email.tsx",
    urlPath: "/dashboard/admin/planner/book-of-the-day/send-creator-email",
    type: "handler",
    precedence: 1,
    module: m75
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/book-of-the-day/set-send-email.tsx",
    urlPath: "/dashboard/admin/planner/book-of-the-day/set-send-email",
    type: "handler",
    precedence: 1,
    module: m76
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/index.tsx",
    urlPath: "/dashboard/admin/planner",
    type: "handler",
    precedence: 1,
    module: m77
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/index.tsx",
    urlPath: "/dashboard/admin/planner/newsletters",
    type: "handler",
    precedence: 1,
    module: m78
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/publisher-of-the-week/send-creator-email.tsx",
    urlPath: "/dashboard/admin/planner/publisher-of-the-week/send-creator-email",
    type: "handler",
    precedence: 1,
    module: m79
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/publisher-of-the-week/set-send-email.tsx",
    urlPath: "/dashboard/admin/planner/publisher-of-the-week/set-send-email",
    type: "handler",
    precedence: 1,
    module: m80
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/spotlight-blurb/generate.tsx",
    urlPath: "/dashboard/admin/planner/spotlight-blurb/generate",
    type: "handler",
    precedence: 1,
    module: m81
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/spotlight-blurb/prepare.tsx",
    urlPath: "/dashboard/admin/planner/spotlight-blurb/prepare",
    type: "handler",
    precedence: 1,
    module: m82
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/stores/create.tsx",
    urlPath: "/dashboard/admin/stores/create",
    type: "handler",
    precedence: 1,
    module: m83
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/stores/index.tsx",
    urlPath: "/dashboard/admin/stores",
    type: "handler",
    precedence: 1,
    module: m84
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/users/create.tsx",
    urlPath: "/dashboard/admin/users/create",
    type: "handler",
    precedence: 1,
    module: m85
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/users/delete-multiple.tsx",
    urlPath: "/dashboard/admin/users/delete-multiple",
    type: "handler",
    precedence: 1,
    module: m86
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/users/index.tsx",
    urlPath: "/dashboard/admin/users",
    type: "handler",
    precedence: 1,
    module: m87
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/analytics/index.tsx",
    urlPath: "/dashboard/analytics",
    type: "handler",
    precedence: 1,
    module: m88
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/import/images/upload.tsx",
    urlPath: "/dashboard/books/import/images/upload",
    type: "handler",
    precedence: 1,
    module: m89
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/import/images.tsx",
    urlPath: "/dashboard/books/import/images",
    type: "handler",
    precedence: 1,
    module: m90
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/import/template.tsx",
    urlPath: "/dashboard/books/import/template",
    type: "handler",
    precedence: 1,
    module: m91
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/import.tsx",
    urlPath: "/dashboard/books/import",
    type: "handler",
    precedence: 1,
    module: m92
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/index.tsx",
    urlPath: "/dashboard/books",
    type: "handler",
    precedence: 1,
    module: m93
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/new.tsx",
    urlPath: "/dashboard/books/new",
    type: "handler",
    precedence: 1,
    module: m94
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/reorder.tsx",
    urlPath: "/dashboard/books/reorder",
    type: "handler",
    precedence: 1,
    module: m95
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/index.tsx",
    urlPath: "/dashboard",
    type: "handler",
    precedence: 1,
    module: m96
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/messages/index.tsx",
    urlPath: "/dashboard/messages",
    type: "handler",
    precedence: 1,
    module: m97
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/about.tsx",
    urlPath: "/hyperview/about",
    type: "handler",
    precedence: 1,
    module: m98
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/accounts.tsx",
    urlPath: "/hyperview/accounts",
    type: "handler",
    precedence: 1,
    module: m99
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/artist-of-the-week.tsx",
    urlPath: "/hyperview/artist-of-the-week",
    type: "handler",
    precedence: 1,
    module: m100
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/auth-modal.tsx",
    urlPath: "/hyperview/auth-modal",
    type: "handler",
    precedence: 1,
    module: m101
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/book-of-the-day.tsx",
    urlPath: "/hyperview/book-of-the-day",
    type: "handler",
    precedence: 1,
    module: m102
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books.tsx",
    urlPath: "/hyperview/books",
    type: "handler",
    precedence: 1,
    module: m103
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/tab/all.tsx",
    urlPath: "/hyperview/creators/tab/all",
    type: "handler",
    precedence: 1,
    module: m104
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/tab/artists.tsx",
    urlPath: "/hyperview/creators/tab/artists",
    type: "handler",
    precedence: 1,
    module: m105
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/tab/following.tsx",
    urlPath: "/hyperview/creators/tab/following",
    type: "handler",
    precedence: 1,
    module: m106
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/tab/publishers.tsx",
    urlPath: "/hyperview/creators/tab/publishers",
    type: "handler",
    precedence: 1,
    module: m107
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators.tsx",
    urlPath: "/hyperview/creators",
    type: "handler",
    precedence: 1,
    module: m108
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs/tab/current.tsx",
    urlPath: "/hyperview/fairs/tab/current",
    type: "handler",
    precedence: 1,
    module: m109
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs/tab/past.tsx",
    urlPath: "/hyperview/fairs/tab/past",
    type: "handler",
    precedence: 1,
    module: m110
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs/tab/upcoming.tsx",
    urlPath: "/hyperview/fairs/tab/upcoming",
    type: "handler",
    precedence: 1,
    module: m111
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs.tsx",
    urlPath: "/hyperview/fairs",
    type: "handler",
    precedence: 1,
    module: m112
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/favorites.tsx",
    urlPath: "/hyperview/favorites",
    type: "handler",
    precedence: 1,
    module: m113
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/fairs.tsx",
    urlPath: "/hyperview/featured/tab/fairs",
    type: "handler",
    precedence: 1,
    module: m114
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/feed.tsx",
    urlPath: "/hyperview/featured/tab/feed",
    type: "handler",
    precedence: 1,
    module: m115
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/groups.tsx",
    urlPath: "/hyperview/featured/tab/groups",
    type: "handler",
    precedence: 1,
    module: m116
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/home-content.tsx",
    urlPath: "/hyperview/featured/tab/home-content",
    type: "handler",
    precedence: 1,
    module: m117
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/interviews.tsx",
    urlPath: "/hyperview/featured/tab/interviews",
    type: "handler",
    precedence: 1,
    module: m118
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/latest-books.tsx",
    urlPath: "/hyperview/featured/tab/latest-books",
    type: "handler",
    precedence: 1,
    module: m119
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/messages.tsx",
    urlPath: "/hyperview/featured/tab/messages",
    type: "handler",
    precedence: 1,
    module: m120
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/stores.tsx",
    urlPath: "/hyperview/featured/tab/stores",
    type: "handler",
    precedence: 1,
    module: m121
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured/tab/trending-creators.tsx",
    urlPath: "/hyperview/featured/tab/trending-creators",
    type: "handler",
    precedence: 1,
    module: m122
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/featured.tsx",
    urlPath: "/hyperview/featured",
    type: "handler",
    precedence: 1,
    module: m123
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/interviews.tsx",
    urlPath: "/hyperview/interviews",
    type: "handler",
    precedence: 1,
    module: m124
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/login.tsx",
    urlPath: "/hyperview/login",
    type: "handler",
    precedence: 1,
    module: m125
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/logout.tsx",
    urlPath: "/hyperview/logout",
    type: "handler",
    precedence: 1,
    module: m126
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/messages.tsx",
    urlPath: "/hyperview/messages",
    type: "handler",
    precedence: 1,
    module: m127
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/privacy.tsx",
    urlPath: "/hyperview/privacy",
    type: "handler",
    precedence: 1,
    module: m128
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/publisher-of-the-week.tsx",
    urlPath: "/hyperview/publisher-of-the-week",
    type: "handler",
    precedence: 1,
    module: m129
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/register.tsx",
    urlPath: "/hyperview/register",
    type: "handler",
    precedence: 1,
    module: m130
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/search.tsx",
    urlPath: "/hyperview/search",
    type: "handler",
    precedence: 1,
    module: m131
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/settings/tab/privacy.tsx",
    urlPath: "/hyperview/settings/tab/privacy",
    type: "handler",
    precedence: 1,
    module: m132
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/settings/tab/terms.tsx",
    urlPath: "/hyperview/settings/tab/terms",
    type: "handler",
    precedence: 1,
    module: m133
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/stores.tsx",
    urlPath: "/hyperview/stores",
    type: "handler",
    precedence: 1,
    module: m134
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/terms.tsx",
    urlPath: "/hyperview/terms",
    type: "handler",
    precedence: 1,
    module: m135
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/this-week.tsx",
    urlPath: "/hyperview/this-week",
    type: "handler",
    precedence: 1,
    module: m136
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/+layout.tsx",
    urlPath: "/hyperview/+layout",
    type: "handler",
    precedence: 1,
    module: m137
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/index.tsx",
    urlPath: "/hyperview",
    type: "handler",
    precedence: 1,
    module: m138
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/botd-advance-notification-emails.tsx",
    urlPath: "/jobs/cron/botd-advance-notification-emails",
    type: "handler",
    precedence: 1,
    module: m139
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/botd-feature-day-emails.tsx",
    urlPath: "/jobs/cron/botd-feature-day-emails",
    type: "handler",
    precedence: 1,
    module: m140
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/ceo-metrics-email.tsx",
    urlPath: "/jobs/cron/ceo-metrics-email",
    type: "handler",
    precedence: 1,
    module: m141
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/creator-analytics-digest.tsx",
    urlPath: "/jobs/cron/creator-analytics-digest",
    type: "handler",
    precedence: 1,
    module: m142
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/creator-milestone-emails.tsx",
    urlPath: "/jobs/cron/creator-milestone-emails",
    type: "handler",
    precedence: 1,
    module: m143
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/creator-profile-share-emails.tsx",
    urlPath: "/jobs/cron/creator-profile-share-emails",
    type: "handler",
    precedence: 1,
    module: m144
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/daily-botd-instagram.tsx",
    urlPath: "/jobs/cron/daily-botd-instagram",
    type: "handler",
    precedence: 1,
    module: m145
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/daily-product-digest.tsx",
    urlPath: "/jobs/cron/daily-product-digest",
    type: "handler",
    precedence: 1,
    module: m146
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/instagram-prep-reminder-email.tsx",
    urlPath: "/jobs/cron/instagram-prep-reminder-email",
    type: "handler",
    precedence: 1,
    module: m147
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/interview-reminder-emails.tsx",
    urlPath: "/jobs/cron/interview-reminder-emails",
    type: "handler",
    precedence: 1,
    module: m148
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/notify-followers-new-books.tsx",
    urlPath: "/jobs/cron/notify-followers-new-books",
    type: "handler",
    precedence: 1,
    module: m149
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/notify-followers-new-posts.tsx",
    urlPath: "/jobs/cron/notify-followers-new-posts",
    type: "handler",
    precedence: 1,
    module: m150
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/planner-content-preview-email.tsx",
    urlPath: "/jobs/cron/planner-content-preview-email",
    type: "handler",
    precedence: 1,
    module: m151
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/spotlight-creator-emails.tsx",
    urlPath: "/jobs/cron/spotlight-creator-emails",
    type: "handler",
    precedence: 1,
    module: m152
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/stub-outreach-emails.tsx",
    urlPath: "/jobs/cron/stub-outreach-emails",
    type: "handler",
    precedence: 1,
    module: m153
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/verification-feedback-emails.tsx",
    urlPath: "/jobs/cron/verification-feedback-emails",
    type: "handler",
    precedence: 1,
    module: m154
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/verified-creator-instagram.tsx",
    urlPath: "/jobs/cron/verified-creator-instagram",
    type: "handler",
    precedence: 1,
    module: m155
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/weekly-botd-newsletter.tsx",
    urlPath: "/jobs/cron/weekly-botd-newsletter",
    type: "handler",
    precedence: 1,
    module: m156
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/jobs/cron/weekly-trending-instagram.tsx",
    urlPath: "/jobs/cron/weekly-trending-instagram",
    type: "handler",
    precedence: 1,
    module: m157
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/robots.txt.tsx",
    urlPath: "/robots.txt",
    type: "handler",
    precedence: 1,
    module: m158
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/sitemap.xml.tsx",
    urlPath: "/sitemap.xml",
    type: "handler",
    precedence: 1,
    module: m159
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/artist-of-the-week/[week].tsx",
    urlPath: "/artist-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m160
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/book-of-the-day/[date].tsx",
    urlPath: "/book-of-the-day/:date",
    type: "handler",
    precedence: 2,
    module: m161
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/books/[slug].tsx",
    urlPath: "/books/:slug",
    type: "handler",
    precedence: 2,
    module: m162
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/books/preview/[slug].tsx",
    urlPath: "/books/preview/:slug",
    type: "handler",
    precedence: 2,
    module: m163
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/books/tags/[tag].tsx",
    urlPath: "/books/tags/:tag",
    type: "handler",
    precedence: 2,
    module: m164
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/creators/[slug].tsx",
    urlPath: "/creators/:slug",
    type: "handler",
    precedence: 2,
    module: m165
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fairs/[slug].tsx",
    urlPath: "/fairs/:slug",
    type: "handler",
    precedence: 2,
    module: m166
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/fragments/related-books/[slug].tsx",
    urlPath: "/fragments/related-books/:slug",
    type: "handler",
    precedence: 2,
    module: m167
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/interviews/[tokenId]/opt-out-reminders.tsx",
    urlPath: "/interviews/:tokenId/opt-out-reminders",
    type: "handler",
    precedence: 2,
    module: m168
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/interviews/[tokenId].tsx",
    urlPath: "/interviews/:tokenId",
    type: "handler",
    precedence: 2,
    module: m169
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/interviews/view/[slug].tsx",
    urlPath: "/interviews/view/:slug",
    type: "handler",
    precedence: 2,
    module: m170
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/out/[slug].tsx",
    urlPath: "/out/:slug",
    type: "handler",
    precedence: 2,
    module: m171
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/publisher-of-the-week/[week].tsx",
    urlPath: "/publisher-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m172
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/stores/[slug].tsx",
    urlPath: "/stores/:slug",
    type: "handler",
    precedence: 2,
    module: m173
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/(app)/users/[userId]/update.tsx",
    urlPath: "/users/:userId/update",
    type: "handler",
    precedence: 2,
    module: m174
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/books/[bookId]/collect.tsx",
    urlPath: "/api/books/:bookId/collect",
    type: "handler",
    precedence: 2,
    module: m175
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/books/[bookId]/comments/[commentId].tsx",
    urlPath: "/api/books/:bookId/comments/:commentId",
    type: "handler",
    precedence: 2,
    module: m176
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/books/[bookId]/comments.tsx",
    urlPath: "/api/books/:bookId/comments",
    type: "handler",
    precedence: 2,
    module: m177
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/books/[bookId]/like.tsx",
    urlPath: "/api/books/:bookId/like",
    type: "handler",
    precedence: 2,
    module: m178
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/books/[bookId]/wishlist.tsx",
    urlPath: "/api/books/:bookId/wishlist",
    type: "handler",
    precedence: 2,
    module: m179
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/creators/[creatorId]/follow.tsx",
    urlPath: "/api/creators/:creatorId/follow",
    type: "handler",
    precedence: 2,
    module: m180
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/fairs/[fairId]/attend.tsx",
    urlPath: "/api/fairs/:fairId/attend",
    type: "handler",
    precedence: 2,
    module: m181
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/api/users/[userId]/profile-image.tsx",
    urlPath: "/api/users/:userId/profile-image",
    type: "handler",
    precedence: 2,
    module: m182
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/[creatorId]/index.tsx",
    urlPath: "/claims/:creatorId",
    type: "handler",
    precedence: 2,
    module: m183
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/[creatorId]/register-and-claim.tsx",
    urlPath: "/claims/:creatorId/register-and-claim",
    type: "handler",
    precedence: 2,
    module: m184
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/[creatorId]/start/signup.tsx",
    urlPath: "/claims/:creatorId/start/signup",
    type: "handler",
    precedence: 2,
    module: m185
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/[creatorId]/start.tsx",
    urlPath: "/claims/:creatorId/start",
    type: "handler",
    precedence: 2,
    module: m186
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/claims/[creatorId].tsx",
    urlPath: "/claims/:creatorId",
    type: "handler",
    precedence: 2,
    module: m187
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/[bookId]/approve.tsx",
    urlPath: "/dashboard/admin/books/:bookId/approve",
    type: "handler",
    precedence: 2,
    module: m188
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/[bookId]/reject.tsx",
    urlPath: "/dashboard/admin/books/:bookId/reject",
    type: "handler",
    precedence: 2,
    module: m189
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/books/[bookId].tsx",
    urlPath: "/dashboard/admin/books/:bookId",
    type: "handler",
    precedence: 2,
    module: m190
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/claims/[claimId]/approve.tsx",
    urlPath: "/dashboard/admin/claims/:claimId/approve",
    type: "handler",
    precedence: 2,
    module: m191
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/claims/[claimId]/reject.tsx",
    urlPath: "/dashboard/admin/claims/:claimId/reject",
    type: "handler",
    precedence: 2,
    module: m192
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId]/delete.tsx",
    urlPath: "/dashboard/admin/creators/:creatorId/delete",
    type: "handler",
    precedence: 2,
    module: m193
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId]/remove-owner.tsx",
    urlPath: "/dashboard/admin/creators/:creatorId/remove-owner",
    type: "handler",
    precedence: 2,
    module: m194
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId]/send-interview.tsx",
    urlPath: "/dashboard/admin/creators/:creatorId/send-interview",
    type: "handler",
    precedence: 2,
    module: m195
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId]/send-welcome-email.tsx",
    urlPath: "/dashboard/admin/creators/:creatorId/send-welcome-email",
    type: "handler",
    precedence: 2,
    module: m196
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId]/toggle-stub-outreach-opt-out.tsx",
    urlPath: "/dashboard/admin/creators/:creatorId/toggle-stub-outreach-opt-out",
    type: "handler",
    precedence: 2,
    module: m197
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/[creatorId].tsx",
    urlPath: "/dashboard/admin/creators/:creatorId",
    type: "handler",
    precedence: 2,
    module: m198
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/assign-owner/[creatorId].tsx",
    urlPath: "/dashboard/admin/creators/assign-owner/:creatorId",
    type: "handler",
    precedence: 2,
    module: m199
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/creators/assign-owner-content/[creatorId].tsx",
    urlPath: "/dashboard/admin/creators/assign-owner-content/:creatorId",
    type: "handler",
    precedence: 2,
    module: m200
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId]/approve.tsx",
    urlPath: "/dashboard/admin/fairs/:fairId/approve",
    type: "handler",
    precedence: 2,
    module: m201
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId]/attendees/[attendeeId]/approve.tsx",
    urlPath: "/dashboard/admin/fairs/:fairId/attendees/:attendeeId/approve",
    type: "handler",
    precedence: 2,
    module: m202
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId]/attendees/[attendeeId]/reject.tsx",
    urlPath: "/dashboard/admin/fairs/:fairId/attendees/:attendeeId/reject",
    type: "handler",
    precedence: 2,
    module: m203
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId]/attendees.tsx",
    urlPath: "/dashboard/admin/fairs/:fairId/attendees",
    type: "handler",
    precedence: 2,
    module: m204
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId]/reject.tsx",
    urlPath: "/dashboard/admin/fairs/:fairId/reject",
    type: "handler",
    precedence: 2,
    module: m205
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/fairs/[fairId].tsx",
    urlPath: "/dashboard/admin/fairs/:fairId",
    type: "handler",
    precedence: 2,
    module: m206
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/interviews/[interviewId].tsx",
    urlPath: "/dashboard/admin/interviews/:interviewId",
    type: "handler",
    precedence: 2,
    module: m207
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/notifications/[notificationId]/read.tsx",
    urlPath: "/dashboard/admin/notifications/:notificationId/read",
    type: "handler",
    precedence: 2,
    module: m208
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/artist-of-the-week/[week]/create.tsx",
    urlPath: "/dashboard/admin/planner/artist-of-the-week/:week/create",
    type: "handler",
    precedence: 2,
    module: m209
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/artist-of-the-week/[week].tsx",
    urlPath: "/dashboard/admin/planner/artist-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m210
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/book-of-the-day/[date]/create.tsx",
    urlPath: "/dashboard/admin/planner/book-of-the-day/:date/create",
    type: "handler",
    precedence: 2,
    module: m211
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/book-of-the-day/[date].tsx",
    urlPath: "/dashboard/admin/planner/book-of-the-day/:date",
    type: "handler",
    precedence: 2,
    module: m212
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/book-of-the-day/[week]/randomize.tsx",
    urlPath: "/dashboard/admin/planner/book-of-the-day/:week/randomize",
    type: "handler",
    precedence: 2,
    module: m213
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/creators/[creatorId]/edit-email.tsx",
    urlPath: "/dashboard/admin/planner/creators/:creatorId/edit-email",
    type: "handler",
    precedence: 2,
    module: m214
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/featured-hero/[week]/prepare.tsx",
    urlPath: "/dashboard/admin/planner/featured-hero/:week/prepare",
    type: "handler",
    precedence: 2,
    module: m215
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/instagram/[week]/clear.tsx",
    urlPath: "/dashboard/admin/planner/instagram/:week/clear",
    type: "handler",
    precedence: 2,
    module: m216
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/instagram/[week]/prepare.tsx",
    urlPath: "/dashboard/admin/planner/instagram/:week/prepare",
    type: "handler",
    precedence: 2,
    module: m217
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/delete.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/delete",
    type: "handler",
    precedence: 2,
    module: m218
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/mark-sent.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/mark-sent",
    type: "handler",
    precedence: 2,
    module: m219
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/regenerate.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/regenerate",
    type: "handler",
    precedence: 2,
    module: m220
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/save.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/save",
    type: "handler",
    precedence: 2,
    module: m221
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/send-brevo-test.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/send-brevo-test",
    type: "handler",
    precedence: 2,
    module: m222
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/newsletters/[campaignId]/send-brevo.tsx",
    urlPath: "/dashboard/admin/planner/newsletters/:campaignId/send-brevo",
    type: "handler",
    precedence: 2,
    module: m223
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/publisher-of-the-week/[week]/create.tsx",
    urlPath: "/dashboard/admin/planner/publisher-of-the-week/:week/create",
    type: "handler",
    precedence: 2,
    module: m224
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/publisher-of-the-week/[week].tsx",
    urlPath: "/dashboard/admin/planner/publisher-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m225
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/spotlight-copy/[week]/generate.tsx",
    urlPath: "/dashboard/admin/planner/spotlight-copy/:week/generate",
    type: "handler",
    precedence: 2,
    module: m226
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/planner/spotlight-copy/[week]/prepare.tsx",
    urlPath: "/dashboard/admin/planner/spotlight-copy/:week/prepare",
    type: "handler",
    precedence: 2,
    module: m227
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/stores/[storeId]/approve.tsx",
    urlPath: "/dashboard/admin/stores/:storeId/approve",
    type: "handler",
    precedence: 2,
    module: m228
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/stores/[storeId]/reject.tsx",
    urlPath: "/dashboard/admin/stores/:storeId/reject",
    type: "handler",
    precedence: 2,
    module: m229
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/stores/[storeId].tsx",
    urlPath: "/dashboard/admin/stores/:storeId",
    type: "handler",
    precedence: 2,
    module: m230
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/users/[userId]/reset-password.tsx",
    urlPath: "/dashboard/admin/users/:userId/reset-password",
    type: "handler",
    precedence: 2,
    module: m231
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/admin/users/[userId].tsx",
    urlPath: "/dashboard/admin/users/:userId",
    type: "handler",
    precedence: 2,
    module: m232
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/[bookId]/publisher.tsx",
    urlPath: "/dashboard/books/:bookId/publisher",
    type: "handler",
    precedence: 2,
    module: m233
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/[bookId]/resubmit.tsx",
    urlPath: "/dashboard/books/:bookId/resubmit",
    type: "handler",
    precedence: 2,
    module: m234
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/books/[bookId].tsx",
    urlPath: "/dashboard/books/:bookId",
    type: "handler",
    precedence: 2,
    module: m235
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/creators/[creatorId].tsx",
    urlPath: "/dashboard/creators/:creatorId",
    type: "handler",
    precedence: 2,
    module: m236
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/books/[bookId]/cover.tsx",
    urlPath: "/dashboard/images/books/:bookId/cover",
    type: "handler",
    precedence: 2,
    module: m237
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/books/[bookId]/gallery.tsx",
    urlPath: "/dashboard/images/books/:bookId/gallery",
    type: "handler",
    precedence: 2,
    module: m238
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/creators/[creatorId]/banner.tsx",
    urlPath: "/dashboard/images/creators/:creatorId/banner",
    type: "handler",
    precedence: 2,
    module: m239
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/creators/[creatorId]/cover.tsx",
    urlPath: "/dashboard/images/creators/:creatorId/cover",
    type: "handler",
    precedence: 2,
    module: m240
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/fairs/[fairId]/banner.tsx",
    urlPath: "/dashboard/images/fairs/:fairId/banner",
    type: "handler",
    precedence: 2,
    module: m241
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/fairs/[fairId]/cover.tsx",
    urlPath: "/dashboard/images/fairs/:fairId/cover",
    type: "handler",
    precedence: 2,
    module: m242
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/stores/[storeId]/cover.tsx",
    urlPath: "/dashboard/images/stores/:storeId/cover",
    type: "handler",
    precedence: 2,
    module: m243
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/images/users/[userId]/profile.tsx",
    urlPath: "/dashboard/images/users/:userId/profile",
    type: "handler",
    precedence: 2,
    module: m244
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/messages/[creatorId]/[messageId].tsx",
    urlPath: "/dashboard/messages/:creatorId/:messageId",
    type: "handler",
    precedence: 2,
    module: m245
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/dashboard/messages/[creatorId].tsx",
    urlPath: "/dashboard/messages/:creatorId",
    type: "handler",
    precedence: 2,
    module: m246
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/artist-of-the-week/[week].tsx",
    urlPath: "/hyperview/artist-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m247
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/book-of-the-day/[date].tsx",
    urlPath: "/hyperview/book-of-the-day/:date",
    type: "handler",
    precedence: 2,
    module: m248
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/artist-books/[artistId].tsx",
    urlPath: "/hyperview/books/:bookId/tab/artist-books/:artistId",
    type: "handler",
    precedence: 2,
    module: m249
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/artist.tsx",
    urlPath: "/hyperview/books/:bookId/tab/artist",
    type: "handler",
    precedence: 2,
    module: m250
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/book-content.tsx",
    urlPath: "/hyperview/books/:bookId/tab/book-content",
    type: "handler",
    precedence: 2,
    module: m251
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/book.tsx",
    urlPath: "/hyperview/books/:bookId/tab/book",
    type: "handler",
    precedence: 2,
    module: m252
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/comments.tsx",
    urlPath: "/hyperview/books/:bookId/tab/comments",
    type: "handler",
    precedence: 2,
    module: m253
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/publisher-books/[publisherId].tsx",
    urlPath: "/hyperview/books/:bookId/tab/publisher-books/:publisherId",
    type: "handler",
    precedence: 2,
    module: m254
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/books/[bookId]/tab/publisher.tsx",
    urlPath: "/hyperview/books/:bookId/tab/publisher",
    type: "handler",
    precedence: 2,
    module: m255
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/about.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/about",
    type: "handler",
    precedence: 2,
    module: m256
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/artists.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/artists",
    type: "handler",
    precedence: 2,
    module: m257
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/books-content.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/books-content",
    type: "handler",
    precedence: 2,
    module: m258
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/books.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/books",
    type: "handler",
    precedence: 2,
    module: m259
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/messages.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/messages",
    type: "handler",
    precedence: 2,
    module: m260
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[creatorId]/tab/publishers.tsx",
    urlPath: "/hyperview/creators/:creatorId/tab/publishers",
    type: "handler",
    precedence: 2,
    module: m261
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/creators/[id]/tab/books-content.tsx",
    urlPath: "/hyperview/creators/:id/tab/books-content",
    type: "handler",
    precedence: 2,
    module: m262
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs/[slug]/attending-creators.tsx",
    urlPath: "/hyperview/fairs/:slug/attending-creators",
    type: "handler",
    precedence: 2,
    module: m263
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/fairs/[slug].tsx",
    urlPath: "/hyperview/fairs/:slug",
    type: "handler",
    precedence: 2,
    module: m264
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/interviews/view/[slug].tsx",
    urlPath: "/hyperview/interviews/view/:slug",
    type: "handler",
    precedence: 2,
    module: m265
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/publisher-of-the-week/[week].tsx",
    urlPath: "/hyperview/publisher-of-the-week/:week",
    type: "handler",
    precedence: 2,
    module: m266
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/stores/[slug].tsx",
    urlPath: "/hyperview/stores/:slug",
    type: "handler",
    precedence: 2,
    module: m267
  },
  {
    filePath: "/Users/eannafreeney/Code/photobookers/src/fs-routes/hyperview/(app)/tags/[tag].tsx",
    urlPath: "/hyperview/tags/:tag",
    type: "handler",
    precedence: 2,
    module: m268
  }
];
