import { registerAddCreatorFormAdmin } from "../features/dashboard/admin/creators/client/addCreatorFormAdmin";
import { registerBookFormAdmin } from "../features/dashboard/admin/books/client/bookFormAdmin";
import { registerFairFormAdmin } from "../features/dashboard/admin/fairs/client/fairFormAdmin";
import { registerBookOfTheDayForm } from "../features/dashboard/admin/planner/client/bookOfTheDayForm";
import { registerEditCreatorFormAdmin } from "../features/dashboard/admin/creators/client/editCreatorFormAdmin";
import { registerNewUserForm } from "../features/dashboard/admin/users/client/newUserForm";
import { registerAOTWForm } from "../features/dashboard/admin/planner/client/aotwForm";
import { registerPOTWForm } from "../features/dashboard/admin/planner/client/potwForm";
import { registerSpotlightBlurbModal } from "../features/dashboard/admin/planner/client/spotlightBlurbModal";
import { registerAdminNotificationsBadge } from "../features/dashboard/admin/notifications/client/adminNotificationsBadge";
import { registerAdminClaimsBadge } from "../features/dashboard/admin/claims/client/adminClaimsBadge";
import { registerEditInterviewForm } from "../features/dashboard/admin/interviews/client/editInterviewForm";
import { registerFairCoverForm } from "../features/dashboard/admin/fairs/client/fairCoverForm";
import { registerFairBannerForm } from "../features/dashboard/admin/fairs/client/fairBannerForm";
import { registerStoreFormAdmin } from "../features/dashboard/admin/stores/client/storeFormAdmin";
import { registerStoreCoverForm } from "../features/dashboard/admin/stores/client/storeCoverForm";
import { registerBookCoverForm } from "../features/dashboard/books/client/bookCoverForm";
import { registerBookGalleryForm } from "../features/dashboard/books/client/bookGalleryForm";
import { registerBooksTableReorder } from "../features/dashboard/books/client/booksTableReorder";
import { registerCreatorCoverForm } from "../features/dashboard/creators/client/creatorCoverForm";

registerAdminClaimsBadge();
registerAddCreatorFormAdmin();
registerBookFormAdmin();
registerFairFormAdmin();
registerBookOfTheDayForm();
registerEditCreatorFormAdmin();
registerNewUserForm();
registerAOTWForm();
registerPOTWForm();
registerSpotlightBlurbModal();
registerAdminNotificationsBadge();
registerEditInterviewForm();
registerFairCoverForm();
registerFairBannerForm();
registerStoreFormAdmin();
registerStoreCoverForm();
registerBookCoverForm();
registerBookGalleryForm();
registerBooksTableReorder();
registerCreatorCoverForm();

// main.js sets window.Alpine and defers start() until this bundle runs.
(window as unknown as { Alpine: { start: () => void } }).Alpine.start();
