import { registerLoginForm } from "../features/auth/client/loginForm";
import { registerForgotPasswordForm } from "../features/auth/client/forgotPasswordForm";
import { registerEditCreatorForm } from "../features/dashboard/creators/client/editCreatorForm";
import { registerBookForm } from "../features/dashboard/books/client/bookForm";
import { registerCarouselForm } from "../features/dashboard/images/client/carouselForm";
import { registerBookCoverForm } from "../features/dashboard/books/client/bookCoverForm";
import { registerCreatorCoverForm } from "../features/dashboard/creators/client/creatorCoverForm";
import { registerComboBox } from "./components/comboBox";
import { registerBookGalleryForm } from "../features/dashboard/books/client/bookGalleryForm";
import { registerClaimForm } from "../features/claims/client/claimForm";
import { registerCountryForm } from "../features/app/client/countryForm";
import { registerShareButton } from "./components/shareButton";
import { registerRegisterFanForm } from "../features/auth/client/registerFanForm";
import { registerRegisterCreatorForm } from "../features/auth/client/registerCreatorForm";
import { registerResetPasswordForm } from "../features/auth/client/resetPasswordForm";
import { registerImageOrientation } from "./utils/imageOrientation";
import { registerContactForm } from "../features/app/client/contactForm";
import { registerBookFilters } from "../features/app/client/bookFilters";
import { registerClaimSignupForm } from "../features/claims/client/claimSignUpForm";
import { registerUserProfileImageForm } from "../features/app/client/userProfileImageForm";
import { registerCommentForm } from "../features/api/client/commentForm";
import { registerHeroCarousel } from "./components/heroCarousel";
import { registerHorizontalScrollGallery } from "./components/horizontalScrollGallery";
import { registerCountUp } from "../features/app/client/countUp";
import { registerAlert } from "./components/alert";
import { registerActivityFeed } from "./components/activityFeed";
import { registerInterviewForm } from "../features/interviews/client/interviewForm";
import { registerMessageForm } from "../features/dashboard/messages/client/messageForm";
import { registerCreatorBannerForm } from "../features/dashboard/images/client/creatorBannerForm";
import { registerBulkCoverUpload } from "./components/bulkCoverUpload";
import { registerStoresMap } from "../features/app/stores/client/storesMap";
import { registerOptionsComboBox } from "./components/optionsComboBox";

registerLoginForm();
registerForgotPasswordForm();
registerRegisterFanForm();
registerRegisterCreatorForm();
registerEditCreatorForm();
registerBookForm();
registerCarouselForm();
registerBookCoverForm();
registerCreatorCoverForm();
registerComboBox();
registerBookGalleryForm();
registerBulkCoverUpload();
registerClaimForm();
registerCountryForm();
registerShareButton();
registerResetPasswordForm();
registerImageOrientation();
registerContactForm();
registerBookFilters();
registerClaimSignupForm();
registerUserProfileImageForm();
registerCommentForm();
registerHeroCarousel();
registerHorizontalScrollGallery();
registerCountUp();
registerAlert();
registerActivityFeed();
registerInterviewForm();
registerMessageForm();
registerCreatorBannerForm();
registerStoresMap();
registerOptionsComboBox();
