import { registerLoginForm } from "./forms/loginForm";
import { registerCreatorForm } from "./forms/creatorForm";
import { registerBookForm } from "./forms/bookForm";
import { registerCarouselForm } from "./forms/carouselForm";
import { registerBookCoverForm } from "./forms/bookCoverForm";
import { registerCreatorCoverForm } from "./forms/creatorCoverForm";
import { registerComboBox } from "./components/comboBox";
import { registerBookGalleryForm } from "./forms/bookGalleryForm";
import { registerClaimForm } from "./forms/claimForm";
import { registerCountryForm } from "./forms/countryForm";
// import { registerShareButton } from "./components/shareButton";
import { registerImageOrientation } from "./utils/imageOrientation";
import { registerRegisterFanForm } from "./forms/registerFanForm";
import { registerRegisterCreatorForm } from "./forms/registerCreatorForm";
import { registerCreatorFormAdmin } from "./forms/creatorFormAdmin";
import { registerBookFormAdmin } from "./forms/bookFormAdmin";

// Register all Alpine.js data components
registerLoginForm();
registerRegisterFanForm();
registerRegisterCreatorForm();
registerCreatorForm();
registerBookForm();
registerCarouselForm();
registerBookCoverForm();
registerCreatorCoverForm();
registerComboBox();
registerBookGalleryForm();
registerClaimForm();
registerCountryForm();
// registerShareButton();
registerImageOrientation();
registerCreatorFormAdmin();
registerBookFormAdmin();
