import { registerLoginForm } from "../features/auth/client/loginForm";
import { registerEditCreatorForm } from "../features/dashboard/creators/client/editCreatorForm";
import { registerBookForm } from "../features/dashboard/books/client/bookForm";
import { registerCarouselForm } from "../features/dashboard/images/client/carouselForm";
import { registerBookCoverForm } from "../features/dashboard/books/client/bookCoverForm";
import { registerCreatorCoverForm } from "../features/dashboard/creators/client/creatorCoverForm";
import { registerComboBox } from "./components/comboBox";
import { registerBookGalleryForm } from "../features/dashboard/books/client/bookGalleryForm";
import { registerClaimForm } from "../features/claims/client/claimForm";
import { registerCountryForm } from "../features/app/client/countryForm";
import { registerShareButton } from "./components/shareButton";
import { registerRegisterFanForm } from "../features/auth/client/registerFanForm";
import { registerRegisterCreatorForm } from "../features/auth/client/registerCreatorForm";
import { registerAddCreatorFormAdmin } from "../features/dashboard/admin/creators/client/addCreatorFormAdmin";
import { registerBookFormAdmin } from "../features/dashboard/admin/books/client/bookFormAdmin";
import { registerBookOfTheWeekForm } from "../features/dashboard/admin/planner/client/bookOfTheWeekForm";
import { registerEditCreatorFormAdmin } from "../features/dashboard/admin/creators/client/editCreatorFormAdmin";
import { registerNewUserForm } from "../features/dashboard/admin/users/client/newUserForm";
import { registerResetPasswordForm } from "../features/auth/client/resetPasswordForm";
import { registerImageOrientation } from "./utils/imageOrientation";
import { registerContactForm } from "../features/app/client/contactForm";
import { registerFeaturedForm } from "../features/dashboard/admin/planner/client/featuredForm";

// Register all Alpine.js data components
registerLoginForm();
registerRegisterFanForm();
registerRegisterCreatorForm();
registerEditCreatorForm();
registerBookForm();
registerCarouselForm();
registerBookCoverForm();
registerCreatorCoverForm();
registerComboBox();
registerBookGalleryForm();
registerClaimForm();
registerCountryForm();
registerShareButton();
registerAddCreatorFormAdmin();
registerBookFormAdmin();
registerBookOfTheWeekForm();
registerEditCreatorFormAdmin();
registerNewUserForm();
registerResetPasswordForm();
registerImageOrientation();
registerContactForm();
registerFeaturedForm();
