import { registerLoginForm } from "../features/auth/client/loginForm";
import { registerForgotPasswordForm } from "../features/auth/client/forgotPasswordForm";
import { registerRegisterFanForm } from "../features/auth/client/registerFanForm";
import { registerRegisterCreatorForm } from "../features/auth/client/registerCreatorForm";
import { registerResetPasswordForm } from "../features/auth/client/resetPasswordForm";
import { registerClaimForm } from "../features/claims/client/claimForm";
import { registerClaimSignupForm } from "../features/claims/client/claimSignUpForm";
import { registerCountryForm } from "../features/app/client/countryForm";
import { registerContactForm } from "../features/app/client/contactForm";
import { registerBookFilters } from "../features/app/client/bookFilters";
import { registerCommentForm } from "../features/api/client/commentForm";
import { registerComboBox } from "./components/comboBox";
import { registerShareButton } from "./components/shareButton";
import { registerImageOrientation } from "./utils/imageOrientation";
import { registerHeroCarousel } from "./components/heroCarousel";
import { registerHorizontalScrollGallery } from "./components/horizontalScrollGallery";
import { registerCarouselForm } from "../features/dashboard/images/client/carouselForm";
import { registerCountUp } from "../features/app/client/countUp";
import { registerAlert } from "./components/alert";
import { registerActivityFeed } from "./components/activityFeed";
import { registerOptionsComboBox } from "./components/optionsComboBox";

registerLoginForm();
registerForgotPasswordForm();
registerRegisterFanForm();
registerRegisterCreatorForm();
registerResetPasswordForm();
registerClaimForm();
registerClaimSignupForm();
registerCountryForm();
registerContactForm();
registerBookFilters();
registerCommentForm();
registerComboBox();
registerShareButton();
registerImageOrientation();
registerHeroCarousel();
registerHorizontalScrollGallery();
registerCarouselForm();
registerCountUp();
registerAlert();
registerActivityFeed();
registerOptionsComboBox();
